version: "3.7"
services:
  app1:
    build: ./src/app1
    command: ["/src/app1/run.sh"]
    volumes:
      - static_volume:/app1/staticfiles
    environment:
      RDB_URI: "postgres://USER:PASSWORD@relationdb:5432/DB_NAME"
      NOSQL_DB_URI: "mongodb://USER:PASSWORD@nosqldb:27017"
    restart: always

  app2:
    build: ./src/app2
    command: ["/src/app2/run.sh"]
    volumes:
      - static_volume:/app2/staticfiles
    environment:
      RDB_URI: "postgres://USER:PASSWORD@relationdb:5432/DB_NAME"
      NOSQL_DB_URI: "mongodb://USER:PASSWORD@nosqldb:27017"
    restart: always

  relationdb:
    build: ./src/relationdb
    image: postgres:12.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    stdin_open: true
    restart: always
    ports:
      - 5432:5432
    networks:
      - network-relationdb
    environment:
      POSTGRES_USER: "USER"
      POSTGRES_PASSWORD: "PASSWORD"
      POSTGRES_DB: "DB_NAME"
    restart: always

  nosqldb:
    build: ./src/nosqldb
    image: mongo:latest
    volumes:
      - ./src/nosqldb:/src/nosqldb
    stdin_open: true
    restart: always
    ports:
      - 27017:27017
    networks:
      - network-nosqldb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "rootPassXXX"
    restart: always

networks:
  network-relationdb:
  network-nosqldb:

volumes:
  postgres_data:
  static_volume:
